### ISSUE TITLE
项目中使用了较多拼接 SQL 语句的方式进行数据库操作，是否存在 SQL 注入风险？

### ISSUE THREAD

**Issue by wjq990112** [SephirothKid/nest-zero-to-one#5]

**Comment by SephirothKid** [comment]
关于这个项目中使用原生SQL语句，有如下几个原因：
1. 这个只是从0到1的教程，重点放在怎么搭建一个较完整的后端服务项目，所以对数据库的操作，尽量从简，避免喧宾夺主；
2. 教程其实是为了前端准备的，大多数读者没有后端实战经验，使用原生语句可以快速进入主题，实现建表、增、删、改、查的功能，也可让读者日后夯实SQL基础，避免知其然而不知其所以然；
3. 关于SQL注入风险，可以使用拦截器或配合DTO进行参数校验。亦可使用TypeORM、SequelizeORM等工具进行数据库操作，这些教程，官方都有，所以也不在教程中赘述了；
